import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

function load(): { words: string[]; source: string } {
  try {
    const m = require('naughty-words') as { en?: unknown };
    if (Array.isArray(m.en)) return { words: m.en as string[], source: 'naughty-words (List of Dirty, Naughty, Obscene and Otherwise Bad Words), CC-BY-4.0' };
  } catch { /* try the next package */ }
  try {
    const m = require('badwords-list') as { array?: unknown };
    if (Array.isArray(m.array)) return { words: m.array as string[], source: 'badwords-list' };
  } catch { /* nothing installed */ }
  throw new Error('Install a word list first: npm install -D naughty-words');
}

const { words, source } = load();
const clean = [...new Set(words.map(w => w.toLowerCase().trim()))].filter(w => /^[a-z]+$/.test(w));
const keep = clean.filter(w => w.length >= 4 && w.length <= 12).sort();
const short = clean.filter(w => w.length === 3).sort();
writeFileSync(
  'packages/data/src/safety-generated.ts',
  `// Generated by scripts/build-safety.ts from ${source}. Do not edit by hand.\n` +
    `// Used only to reject invented words that contain one of these fragments.\n` +
    `export const COINED_SUBSTRINGS: readonly string[] = ${JSON.stringify(keep)};\n`,
);
console.log(`Wrote ${keep.length} fragments from ${source}.`);
console.log(`Review these 3-letter entries; copy only slurs into EXTRA_SHORT_FRAGMENTS in safety.ts: ${short.join(', ')}`);
